# Generated by Django 5.1.1 on 2024-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
